<?php require "templates/partials/_header.phtml" ?>

<section class="all-matchs">
    <h2 class="title">LES MATCHS</h2>

    <div class="container_match">
    
        <?php foreach($data as $game): ?>
            <article class="game-card">
                <?php require "templates/partials/_detail_matchs.phtml"?> 

                <a href="index.php?route=match&&game=<?= $game->getName()?>" id="detail_du_match">DETAILS DU MATCH</a>           
            </article>        
        <?php endforeach ?>

    <div>
</section>