<section class="nos-services">
    <p>NOS SERVICES</p>
    <div class="grid-container">
        <?php foreach ($data["services"] as $key => $article): ?>
            <div class="service-card">
                <img src="assets/images/<?=$article["image"]?>" alt="">
                <div class="card-content">
                    <h2><?= $article["name"] ?></h2>
                    <h3><?= $article["tagline"] ?></h3>
                    <h4><?= $article["description"] ?></h4>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</section>