<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=a-propos">À propos</a>
					</li>
                    <li>
						<a href="index.php?route=contact">Contact</a>
					</li>
				</ul>
			</nav>
		</header>
		<?php
			if(isset($_GET["route"])) {
                if($_GET["route"] === "home")
                {
                    require "templates/home.phtml";
                }
                elseif($_GET["route"] === "a-propos")
                {
                    require "templates/about.phtml";
                }
                elseif($_GET["route"] === "notFound")
                {
                    require "templates/notFound.phtml";
                }
                elseif($_GET["route"] === "contact")
                {
                    require "templates/contact.phtml";
                }
            }
            else
            {
                require "templates/home.phtml";
            }
		?>
	</body>
</html>