<section id="players">
    <h2>LES PLAYERS DE LA LEAGUE</h2>
    <ul>
        <?php foreach($data as $player): ?>
            <li>
                <img src="<?= $player->getPortrait()->getUrl() ?>" alt="<?= $player->getPortrait()->getAlt() ?>">
                <h3><?= $player->getNickname() ?></h3>
                <h4><?= $player->getTeam()->getname() ?></h4>
                <a href="index.php?route=players&&name=<?=$player->getNickname()?>">DECOUVREZ <?= $player->getNickname() ?></a>
            </li>
        <?php endforeach ?>
    </ul>
</section>
