<?php require "templates/partials/_header.phtml"?>

<?php foreach($data["game"] as $game): ?>
            
    <?php if ($_GET["game"]===$game->getName()):

        require "templates/partials/_detail_matchs.phtml";
                
        endif;

                          
endforeach ?>
<h2>LES PERFORMANCES</h2>
<table>
  <thead>
    <tr>
      <th>PLAYER</th>
      <th>TEAM</th>
      <th>POINTS</th>
      <th>ASSISTS</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($data["performance"] as $perf):?>
       <?php if($_GET['game']===$perf->getGame()->getName()):?>
    <tr>
      <td> <?= $perf->getPlayer()->getNickname()?> </td>
      <td><?= $perf->getPlayer()->getTeam()->getname()?></td>
      <td><?= $perf->getPoints()?></td>
      <td><?= $perf->getAssists()?></td>
    </tr>
    <?php endif; ?>
    <?php endforeach?>    
  </tbody>
</table>

