<!DOCTYPE html>
<link rel="stylesheet" href="styles/style-accueil.css">
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Home</title>
    </head>
    <body>
        <main>
        <section class="hero-text">
            <h1>YEPIFY</h1>
            <p>Les meilleurs Yep, partout, tout le temps.</p>
        </section>

        <section class="music-card">
            <div class="card-header">
                <div class="song-info">
                    <h3>Yeppy Yeah</h3>
                    <div class="flex-tree">
                        <h2>I'm feeling Yep</h2>
                        <img src="assets/tree.png" alt="">
                    </div>
                </div>
                <div class="album-art"></div>
            </div>

            <ul class="playlist">
                <li class="active">
                    <div class="icon-container">
                        <img src="assets/equalizer.png" alt="Graphique" class="active-icon">
                    </div>
                    Yeppin'on a prayer
                </li>

                <li>
                    <div class="icon-container play-icon-wrapper">
                        <img src="assets/play.png" alt="Graphique" class="active-icon">
                    </div>
                    Yep it be
                </li>
                <li>
                    <div class="icon-container play-icon-wrapper">
                        <img src="assets/play.png" alt="Graphique" class="active-icon">
                    </div>
                    Yeppin on the dock of the bay
                </li>
                <li>
                    <div class="icon-container play-icon-wrapper">
                        <img src="assets/play.png" alt="Graphique" class="active-icon">
                    </div>
                    Because the yep
                </li>
                <li>
                    <div class="icon-container play-icon-wrapper">
                        <img src="assets/play.png" alt="Graphique" class="active-icon">
                    </div>
                    Leaving Las Yepas
                </li>
                <li>
                    <div class="icon-container play-icon-wrapper">
                        <img src="assets/play.png" alt="Graphique" class="active-icon">
                    </div>
                    Enter Yepman
                </li>
                <li>
                    <div class="icon-container play-icon-wrapper">
                        <img src="assets/play.png" alt="Graphique" class="active-icon">
                    </div>
                    Fear of the yep
                </li>
            </ul>
        </section>
    </main>
    </body>
</html>