<!DOCTYPE html>
<link rel="stylesheet" href="styles/style-tarif.css">
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Tarifs</title>
    </head>
    <body>
    <h1 class="main-title">Choisissez votre formule</h1>
    <div class="pricing-container">
        <div class="card basic">
            <div class="card-header">
                BASIC
            </div>
            <div class="card-body">
                <ul class="features">
                    <li>Une publicité tous les 3 Yep</li>
                    <li>Zappez 6 Yep par heure</li>
                    <li>Créez vos Yeplist</li>
                    <li>Partagez vos Yeplist</li>
                </ul>
                <div class="price">
                    3.99 $ / mois
                </div>
            </div>
        </div>

        <div class="card premium">
            <div class="card-header">
                PREMIUM
            </div>
            <div class="card-body">
                <ul class="features">
                    <li>Une publicité tous les 20 Yep</li>
                    <li>Zapping de Yep illimité</li>
                    <li>Créez vos Yeplist</li>
                    <li>Créez des Yeplist collaboratives</li>
                    <li>Envoyez des Yeps anonymes</li>
                    <li>Mini studio de création de Yep</li>
                </ul>
                <div class="price">
                    9.99 $ / mois
                </div>
            </div>
        </div>

        <div class="card pro">
            <div class="card-header">
                PRO
            </div>
            <div class="card-body">
                <ul class="features">
                    <li>Une publicité tous les 20 Yep</li>
                    <li>Zapping de Yep illimité</li>
                    <li>Créez vos Yeplist</li>
                    <li>Créez des Yeplist collaboratives</li>
                    <li>Publiez vos Yeps persos</li>
                    <li>Gagnez des royalties sur vos Yeps</li>
                </ul>
                <div class="price">
                    15.99 $ / mois
                </div>
            </div>
        </div>

    </div>
</body>
</html>